LankMark_Restaurant_Management/Models/User.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;

namespace LankMark_Restaurant_Management.Models
{
    public class User
    {
        public String UserID { get; set; }
        public String Password { get; set; }
        public String FullName { get; set; }
        public String EmailAddress { get; set; }
        public String PhoneNumber { get; set; }
        public String UserType { get; set; }
        public double Salary { get; set; }
        public DateTime DateCreateAccount { get; set; }
        public Boolean IsActived { get; set; }
        public Image Avatar { get; set; }

        public User() { }
        public User(string userID, string password, string fullName, string emailAddress, string phoneNumber, string userType, double salary, DateTime dateCreateAccount, bool isActived, Image avatar)
        {
            UserID = userID;
            Password = password;
            FullName = fullName;
            EmailAddress = emailAddress;
            PhoneNumber = phoneNumber;
            UserType = userType;
            Salary = salary;
            DateCreateAccount = dateCreateAccount;
            IsActived = isActived;
            Avatar = avatar;
        }
    }
}

LankMark_Restaurant_Management/Controllers/AccountController.cs
using LankMark_Restaurant_Management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult SignIn()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }    

        public ActionResult UserDetail()
        {
            return View();
        }

    }
}

LankMark_Restaurant_Management/Controllers/CustomerManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class CustomerManagementController : Controller
    {
        // GET: CustomerManagement
        public ActionResult ListCustomer()
        {
            return View();
        }

        public ActionResult Feedback()
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult HomeScreen()
        {
            return View();
        }

    }
}

LankMark_Restaurant_Management/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class NotificationController : Controller
    {
        // GET: Notification
        public ActionResult Notification()
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class ReservationController : Controller
    {
        // GET: Reservation
        public ActionResult ListReservationScreen()
        {
            return View();
        }

        public ActionResult OrderFood()
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Controllers/RestaurantManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class RestaurantManagementController : Controller
    {
        // GET: RestaurantManagement
        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult Storage()
        {
            return View();
        }

        public ActionResult AddToStorage()
        {
            return View();
        }

        public ActionResult AddToMenu()
        {
            return View();
        }

        public ActionResult SupplierManagement()
        {
            return View();
        }

        public ActionResult ImportProductManagement() 
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Controllers/StaffManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class StaffManagementController : Controller
    {
        // GET: StaffManagement
        public ActionResult AddNewStaff()
        {
            return View();
        }
        public ActionResult ListStaff()
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LankMark_Restaurant_Management.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        public ActionResult Statistics()
        {
            return View();
        }
    }
}

LankMark_Restaurant_Management/Views/Partial/Sidebar.cshtml
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="@Url.Action("HomeScreen", "Home")" class="app-brand-link">
            <span style="font-size: 18px; color: #333; font-weight: bold;">LankMark Restaurant</span>
        </a>
        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>
    <div class="menu-inner-shadow"></div>
    <ul class="menu-inner py-1">
        <!-- Home -->
        <li class="menu-item">
            <a href="@Url.Action("HomeScreen", "Home")" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Home</div>
            </a>
        </li>
        <!-- Quản lý đặt bàn -->
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-layout"></i>
                <div data-i18n="Layouts">Quản lý đặt bàn</div>
            </a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="@Url.Action("ListReservationScreen", "Reservation")" class="menu-link">
                        <div data-i18n="Without menu">Đặt bàn</div>
                    </a>
                </li>
                <li class="menu-item ">
                    <a href="@Url.Action("OrderFood", "Reservation")" class="menu-link">
                        <div data-i18n="Without navbar">Đặt món</div>
                    </a>
                </li>
            </ul>
        </li>
        <!-- Quản lý nhà hàng-->
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-dock-top"></i>
                <div data-i18n="Account Settings">Quản lý nhà hàng</div>
            </a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="@Url.Action("Menu", "RestaurantManagement")" class="menu-link">
                        <div data-i18n="Account">Quản lý menu món</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="@Url.Action("Storage", "RestaurantManagement")" class="menu-link">
                        <div data-i18n="Notifications">Quản lý kho hàng</div>
                    </a>
                </li>
                <li class="menu-item admin-menu-item">
                    <a href="@Url.Action("SupplierManagement", "RestaurantManagement")" class="menu-link">
                        <div data-i18n="Notifications">Quản lý nguồn nhập hàng</div>
                    </a>
                </li>
                <li class="menu-item admin-menu-item">
                    <a href="@Url.Action("ImportProductManagement", "RestaurantManagement")" class="menu-link">
                        <div data-i18n="Notifications">Quản lý nhập hàng</div>
                    </a>
                </li>
            </ul>
        </li>
        <!-- Thống kê-->
        <li class="menu-item">
            <a href="@Url.Action("Statistics", "Statistics")" class="menu-link">
                <i class="menu-icon tf-icons bx bx-cube-alt"></i>
                <div data-i18n="Misc">Thống kê</div>
            </a>
        </li>
        <!-- Quản lý nhân viên -->
        <li class="menu-item admin-menu-item">
            <a href="@Url.Action("ListStaff", "StaffManagement")" class="menu-link">
                <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                <div data-i18n="Authentications">Quản lý nhân viên</div>
            </a>
        </li>
        <!--Thông báo-->
        <li class="menu-item admin-menu-item">
            <a href="@Url.Action("Notification", "Notification")" class="menu-link">
                <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                <div data-i18n="Authentications">Thông báo</div>
            </a>
        </li>
    </ul>
</aside>

<script>
    $(document).ready(function () {
        var currentUrl = window.location.href;
        $(".menu-item").each(function () {
            var menuUrl = $(this).find("a").attr("href");
            if (menuUrl && currentUrl.includes(menuUrl)) {
                $(this).addClass("active");
                $(this).parents(".menu-item").addClass("active");
            }
        });
    });

    document.addEventListener('DOMContentLoaded', function () {
        const userDataJSON = sessionStorage.getItem('userData');

        if (!userDataJSON) {
            window.location.href = '@Url.Action("SignIn", "Account")';
            return;
        }

        const userData = JSON.parse(userDataJSON);
        const position = userData.userType;

        if (position === 'Staff') {
            hideAdminMenuItems();
        }
    });

    function hideAdminMenuItems() {
        // Select elements corresponding to menu items not allowed for Staff
        const adminMenuItems = document.querySelectorAll('.admin-menu-item');

        // Hide the admin menu items
        adminMenuItems.forEach(function (element) {
            element.style.display = 'none';
        });
    }
</script>

LankMark_Restaurant_Management/Views/RestaurantManagement/AddToMenu.cshtml
@{
    ViewBag.Title = "AddToMenu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="menu-form">
    <div class="mb-3">
        <label for="foodName" class="form-label">Tên món ăn:</label>
        <input type="text" class="form-control" id="foodName" name="foodName" placeholder="Nhập tên món ăn" required>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Giá:</label>
        <input type="number" class="form-control" id="price" name="price" placeholder="Nhập giá món ăn" required>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Mô tả:</label>
        <textarea class="form-control" id="description" name="description" placeholder="Nhập mô tả về món ăn" required></textarea>
    </div>
    <div class="mb-3">
        <label for="imageFood" class="form-label">Hình ảnh:</label>
        <input type="file" class="form-control" id="imageFood" name="imageFood" accept="image/*" required>
    </div>
    <input type="hidden" id="menuUrl" value="@Url.Action("Menu", "RestaurantManagement")" />
    <div class="mb-3">
        <label for="role" class="form-label">Loại món:</label>
        <select class="form-select" id="role" name="role" required>
            <option value="" selected disabled>Chọn loại món</option>
            <option value="Món chính">Món chính</option>
            <option value="Khai vị">Khai vị</option>
            <option value="Tráng miệng">Tráng miệng</option>
            <option value="Nước">Nước</option>
        </select>
    </div>
    <button type="button" class="btn btn-primary" onclick="confirmAdd()">Thêm món ăn</button>
</form>

<style>
    /* Định dạng các thành phần của form */
    .form-control {
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .form-select {
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
    }

    /* Định dạng nút */
    .btn {
        display: inline-block;
        font-weight: 400;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        user-select: none;
        border: 1px solid transparent;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: 0.25rem;
        transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        cursor: pointer;
    }

    .btn-primary {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            color: #fff;
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .form-select {
        padding: 8px 12px; /* Khoảng cách giữa nội dung và viền của select */
        font-size: 16px; /* Cỡ chữ */
        border-radius: 5px; /* Bo tròn viền */
        border: 1px solid #ccc; /* Viền */
    }

        /* Tạo hiệu ứng khi hover */
        .form-select:hover {
            border-color: #aaa; /* Màu viền khi di chuột qua */
        }

        /* Tạo hiệu ứng khi focus */
        .form-select:focus {
            border-color: #4CAF50; /* Màu viền khi được chọn */
            outline: none; /* Loại bỏ đường viền khi focus */
        }

        /* Tùy chỉnh các option */
        .form-select option {
            background-color: #fff; /* Màu nền của option */
            color: #333; /* Màu chữ của option */
            border-bottom: 1px solid #ccc; /* Tạo border dưới */
        }

            /* Tùy chỉnh khi hover lên các option */
            .form-select option:hover {
                background-color: #f4f4f4; /* Màu nền khi hover */
            }

            /* Tùy chỉnh khi option được chọn */
            .form-select option:checked {
                background-color: #4CAF50; /* Màu nền khi được chọn */
                color: #fff; /* Màu chữ khi được chọn */
            }

        /* Tùy chỉnh style của dropdown arrow */
        .form-select::-ms-expand {
            display: none; /* Ẩn dropdown arrow trên Edge và IE */
        }

        .form-select::after {
            content: "\25BC"; /* Sử dụng một ký tự down-arrow */
            position: absolute;
            top: 50%;
            right: 10px;
            transform: translateY(-50%);
            pointer-events: none; /* Ngăn sự kiện click vào arrow */
        }
</style>

<script type="module" src="~/Scripts/js/firebase/firebaseHelper.js"></script>
<script type="module" src="~/Scripts/js/firebase/addMenu.js"></script>

LankMark_Restaurant_Management/Views/RestaurantManagement/AddToStorage.cshtml
@{
    ViewBag.Title = "AddToStorage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form id="inventory-form">
    <input type="hidden" id="storageUrl" value="@Url.Action("Storage", "RestaurantManagement")" />

    <div class="mb-3">
        <label for="itemName" class="form-label">Tên vật dụng:</label>
        <input type="text" class="form-control" id="itemName" name="itemName" required>
    </div>
    <div class="mb-3">
        <label for="role" class="form-label">Vai trò:</label>
        <select class="form-select" id="role" name="role" required>
            <option value="" disabled selected>Chọn vai trò</option>
            <option value="food">Thực phẩm</option>
            <option value="spices">Gia vị</option>
            <option value="instruments">Dụng cụ</option>
        </select>
    </div>

    <div class="mb-3">
        <label for="quantity" class="form-label">Số lượng:</label>
        <input type="number" class="form-control" id="quantity" name="quantity" required>
    </div>
    <div class="mb-3">
        <label for="minQuantity" class="form-label">Số lượng tối thiểu:</label>
        <input type="number" class="form-control" id="minQuantity" name="minQuantity" required>
    </div>
    <div class="mb-3">
        <label for="unit" class="form-label">Đơn vị tính:</label>
        <select class="form-select" id="unit" name="unit" required>
            <option value="" disabled selected>Chọn đơn vị tính</option>
            <option value="kg">Kilogram (kg)</option>
            <option value="l">Lít (l)</option>
            <option value="piece">Cái (piece)</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Mô tả:</label>
        <textarea class="form-control" id="description" name="description" rows="3"></textarea>
    </div>
    <div class="mb-3">
        <label for="image" class="form-label">Ảnh vật dụng:</label>
        <input type="file" class="form-control" id="image" name="image" accept="image/*">
    </div>
    <button type="submit" class="btn btn-primary">Thêm vật dụng</button>
</form>

<style>
        /* Style cho form */
    #inventory-form {
        max-width: 500px;
        margin: auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Style cho các input và select */
    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    /* Style cho textarea */
    textarea {
        resize: vertical;
    }

    /* Style cho nút submit */
    .btn-primary {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    /* Style cho tiêu đề form */
    .form-label {
        font-weight: bold;
    }

    /* Style cho thông báo lỗi */
    .error-message {
        color: red;
        font-size: 14px;
        margin-top: 5px;
    }

    /* Style cho phần tiêu đề */
    .page-title {
        text-align: center;
        font-size: 24px;
        margin-bottom: 20px;
    }

</style>

<script type="module" src="~/Scripts/js/firebase/firebaseHelper.js"></script>
<script type="module" src="~/Scripts/js/firebase/storageManagement.js"></script>

LankMark_Restaurant_Management/Views/RestaurantManagement/Menu.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="text-align: center; font-size: 24px; font-weight: bold;">MENU</div>
<div class="table-actions">
    <button id="addMenu">Thêm món</button>
</div>
<table>
    <thead>
        <tr>
            <th>Tên món</th>
            <th>Price</th>
            <th>Role</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody id="listMenu">

    </tbody>
</table>

<div id="tableDetailModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeTableDetailModal()">&times;</span>
        <div id="tableDetailContent">
            <!-- Thông tin chi tiết của bàn và danh sách món ăn sẽ được thêm vào đây -->
        </div>
    </div>
</div>

<div class="updateDetail" id="updateDetail">
    <form class="update-detail" id="update-detail">
        <input hidden id="inputMenuKey" />
        <label for="inputFoodName" class="form-label">Tên món:</label>
        <input type="text" id="inputFoodName" name="inputFoodName" required class="form-control"><br>
        <label for="inputfoodPrice" class="form-label">Giá:</label>
        <input type="number" id="inputfoodPrice" name="inputfoodPrice" required class="form-control"><br>
        <label for="inputFoodDescription" class="form-label">Mô tả:</label>
        <textarea class="form-control" id="inputFoodDescription" name="inputFoodDescription" required></textarea><br>
        <label for="imageFood" class="form-label">Hình ảnh:</label>
        <input type="file" class="form-control" id="imageFood" name="imageFood" accept="image/*" required><br>
        <label for="role" class="form-label">Loại món:</label>
        <select class="form-select" id="role" name="role" required>
            <option value="" selected disabled>Chọn loại món</option>
            <option value="Món chính">Món chính</option>
            <option value="Khai vị">Khai vị</option>
            <option value="Tráng miệng">Tráng miệng</option>
            <option value="Nước">Nước</option>
        </select><br />

        <input type="button" class="confirm-button" value="Xác Nhận" onclick="confirmUpdate()">
        <input type="button" class="cancel-button" value="Hủy" onclick="closeUpdateForm()">
    </form>
</div>
<style>
    .table-actions {
        margin-bottom: 20px;
    }

        .table-actions button {
            padding: 8px 16px;
            border: none;
            background-color: #007bff;
            color: white;
            cursor: pointer;
        }

            .table-actions button:hover {
                background-color: #0056b3;
            }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th,
    td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
        font-weight: bold;
    }

    img {
        max-width: 100px;
        max-height: 100px;
    }

    td button {
        padding: 6px 10px;
        margin-right: 5px;
        border: none;
        cursor: pointer;
        border-radius: 4px;
        background-color: #4CAF50;
        color: white;
        font-size: 14px;
    }

        td button:hover {
            background-color: #45a049;
        }

    /*modal*/
    .modal {
        display: none;
        position: fixed;
        z-index: 1000;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4); /* Tạo hiệu ứng mờ nền */
    }

    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        top: 100px;
        border: 1px solid #888;
        width: 75%; /* Điều chỉnh kích thước chiều rộng */
        max-width: 600px; /* Giới hạn kích thước tối đa */
        border-radius: 8px;
        position: relative;
    }

    .close {
        position: absolute;
        top: 0;
        right: 0;
        cursor: pointer;
        padding: 8px;
        font-size: 20px;
    }

    #tableDetailContent {
        max-width: 100%;
        display: block;
    }

    #tableDetailContent img {
        /* Thiết lập kích thước và căn chỉnh cho hình ảnh */
        max-width: 100%;
        max-height: 400px; /* Điều chỉnh kích thước tối đa của hình ảnh */
        display: block;
        margin: 0 auto; /* Căn chỉnh hình ảnh vào giữa */
    }

    /*UpdateDetail*/
    .updateDetail {
        display: none;
        position: fixed;
        z-index: 1000;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4); /* Tạo hiệu ứng mờ nền */
    }

    .update-detail {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        top: 100px;
        border: 1px solid #888;
        width: 75%; /* Điều chỉnh kích thước chiều rộng */
        max-width: 600px; /* Giới hạn kích thước tối đa */
        border-radius: 8px;
        position: relative; /* Đảm bảo modal hiển thị trên sidebar */
    }

    .update-detail label {
        display: block;
        margin-bottom: 10px;
    }

    .update-detail input[type="text"],
    .update-detail input[type="number"],
    .update-detail input[type="file"] {
        width: calc(100% - 20px);
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
    }

    .update-detail .confirm-button {
        width: calc(50% - 10px);
        padding: 10px;
        background-color: #4CAF50;
        color: #fff;
        border: none;
        cursor: pointer;
        opacity: 0.7;
    }

    .update-detail .cancel-button {
        width: calc(50% - 10px);
        padding: 10px;
        background-color: #FF5733;
        color: #fff;
        border: none;
        cursor: pointer;
        opacity: 0.7;
    }

    .update-detail .confirm-button:hover,
    .update-detail .cancel-button:hover {
        opacity: 1;
    }
</style>

<script type="module" src="~/Scripts/js/firebase/firebaseHelper.js"></script>
<script type="module" src="~/Scripts/js/firebase/menuManagement.js"></script>

<script>
    document.getElementById('addMenu').addEventListener('click', function() {
        var url = '@Url.Action("AddToMenu", "RestaurantManagement")';
        window.location.href = url;
    });
</script>

LankMark_Restaurant_Management/Views/StaffManagement/AddNewStaff.cshtml
@{
    ViewBag.Title = "AddNewStaff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form id="signup-form">

    <label for="fullName">Tên nhân viên:</label><br>
    <input type="text" id="fullName" name="fullName" required><br>

    <label for="emailAddress">Email:</label><br>
    <input type="email" id="emailAddress" name="emailAddress" required><br>

    <label for="password">Mật khẩu:</label><br>
    <input type="text" id="password" name="password" readonly value="12345678"><br>

    <label for="phoneNumber">Số điện thoại:</label><br>
    <input type="number" id="phoneNumber" name="phoneNumber" required><br>

    <label for="idCard">Căn cước công dân:</label><br>
    <input type="number" id="idCard" name="idCard" required><br>

    <input type="hidden" id="targetUrl" value="@Url.Action("ListStaff", "StaffManagement")" />

    <label for="userType">Loại nhân viên:</label><br>
    <select id="userType" name="userType">
        <option value="Admin">Admin</option>
        <option value="Manager">Manager</option>
        <option value="Staff">Staff</option>
    </select><br>

    <label for="salary">Lương:</label><br>
    <input type="number" id="salary" name="salary" required><br>

    <input type="submit" value="Tạo tài khoản">
</form>
<script type="module" src="~/Scripts/js/firebase/firebaseHelper.js"></script>
<script src="~/Scripts/js/firebase/signUp.js" type="module"></script>
<style>
    h2 {
        text-align: center;
    }

    form {
        margin: 20px auto;
        background: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"],
    input[type="email"],
    input[type="tel"],
    input[type="password"],
    select,
    input[type="number"],
    input[type="file"],
    input[type="submit"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 3px;
        box-sizing: border-box;
    }

    select {
        height: 40px; /* Đảm bảo chiều cao đồng đều với các input */
    }

    input[type="submit"] {
        background-color: #4caf50;
        color: white;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

    input[type="file"] {
        border: none;
        background-color: transparent;
    }

        input[type="file"]::-webkit-file-upload-button {
            padding: 10px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

            input[type="file"]::-webkit-file-upload-button:hover {
                background-color: #45a049;
            }
</style>